spring:
  jpa:
    show-sql: true
    #    database-platform: mysql
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/study/h2_db/order-db
      username: sa
      password: