spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: order-service
  profiles:
    group:
<<<<<<< HEAD
      local: aws-local
      stage: eureka,aws
=======
      local: aws-local,kakao,db-h2
      stage: eureka,aws,kakao,db-mybatis
>>>>>>> cedc7b6 (application properties 파일 수정)

server:
  port: 28080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: swagger-ui.html