spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: order-service
  profiles:
    group:
      local: aws-local,kakao,db-h2
      stage: eureka,aws,kakao,db-mybatis

server:
  port: 28080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: swagger-ui.html


logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
